name: WorkflowTest
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 